// app/layout.js
import "./globals.css";
import Header from "./components/header/header";
import Footercreative from "./components/footercreatice/page";
import Footer from "./components/footer/page";
import BodyWrapper from "./components/BodyWrapper"; // new client wrapper

import { 
  Raleway, Poppins, Open_Sans, Bebas_Neue, 
  Montserrat, Geist, Geist_Mono 
} from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  display: "swap",
  variable: "--font-raleway",
});
export const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400","800"],
  display: "swap",
});
export const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400","800"],
  display: "swap",
});
export const opensans = Open_Sans({
  variable: "--font-opensans",
  subsets: ["latin"],
  weight: ["400","800"],
  display: "swap",
});
export const bebas_neue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400","800"],
});

export const metadata = {
  title: "Integriti Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${montserrat.variable} ${poppins.variable} ${opensans.variable} ${bebas_neue.variable} ${geistMono.variable} antialiased`}>
        <BodyWrapper>
          <Header />
          {children}
          <Footercreative />
          <Footer />
        </BodyWrapper>
      </body>
    </html>
  );
}
